"""add BackTestTrade

Revision ID: af41b751b50f
Revises: d194e8be4f48
Create Date: 2022-01-16 03:16:51.583115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af41b751b50f'
down_revision = 'd194e8be4f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beck_test_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('buy_time', sa.String(), nullable=False),
    sa.Column('sell_time', sa.String(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('trades', 'createdAt', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beck_test_trades')
    op.alter_column('trades', 'createdAt', existing_type=sa.BigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
