"""init

Revision ID: c3f67ba4cc9c
Revises: 
Create Date: 2022-01-15 17:50:18.917311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f67ba4cc9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kucoin_name', sa.String(), nullable=True),
    sa.Column('binance_name', sa.String(), nullable=True),
    sa.Column('allow_trade', sa.Integer(), nullable=True),
    sa.Column('bought_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kucoin_name')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('opType', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('funds', sa.String(), nullable=True),
    sa.Column('dealFunds', sa.String(), nullable=True),
    sa.Column('dealSize', sa.String(), nullable=True),
    sa.Column('fee', sa.String(), nullable=True),
    sa.Column('feeCurrency', sa.String(), nullable=True),
    sa.Column('stp', sa.String(), nullable=True),
    sa.Column('stop', sa.String(), nullable=True),
    sa.Column('stopTriggered', sa.Integer(), nullable=True),
    sa.Column('stopPrice', sa.String(), nullable=True),
    sa.Column('timeInForce', sa.String(), nullable=True),
    sa.Column('postOnly', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.Column('iceberg', sa.Integer(), nullable=True),
    sa.Column('visibleSize', sa.String(), nullable=True),
    sa.Column('cancelAfter', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('clientOid', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('cancelExist', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.Column('tradeType', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_id', sa.String(), nullable=False),
    sa.Column('sell_id', sa.String(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buy_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['sell_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_pairs')
    op.drop_table('trades')
    op.drop_table('coins')
    # ### end Alembic commands ###
