"""trying relation w/o pkey

Revision ID: d194e8be4f48
Revises: c3f67ba4cc9c
Create Date: 2022-01-16 02:57:01.053240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd194e8be4f48'
down_revision = 'c3f67ba4cc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trades_coin_id_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key('fk_trades_symbol_coins', 'trades', 'coins', ['symbol'], ['kucoin_name'], ondelete='CASCADe')
    op.drop_column('trades', 'coin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('coin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_trades_symbol_coins', 'trades', type_='foreignkey')
    op.create_foreign_key('trades_coin_id_fkey', 'trades', 'coins', ['coin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
